import React from "react";
import { chartUrl } from "../api";

export default function ChartView() {
  return (
    <div className="card">
      <h2>Active Length vs Thickness</h2>
      <p>Chart is generated by the backend from stored records.</p>
      <div className="chart-wrapper">
        <img src={chartUrl()} alt="Active vs Thickness" />
      </div>
    </div>
  );
}